### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by janrop** [codebushi/gatsby-starter-stellar#1]
HI there,

unfortunately the build fails

    error Generating CSS failed

      BrowserslistError: Unknown browser query `dead`

      - index.js:37 error
        [test-stellar]/[browserslist]/index.js:37:11

      - index.js:222
        [test-stellar]/[browserslist]/index.js:222:9

      - Array.forEach

      - index.js:196 browserslist
        [test-stellar]/[browserslist]/index.js:196:13

      - index.js:65 isSupported
        [test-stellar]/[caniuse-api]/dist/index.js:65:37

      - index.js:69
        [test-stellar]/[postcss-cssnext]/lib/index.js:69:117

      - Array.forEach

      - index.js:56
        [test-stellar]/[postcss-cssnext]/lib/index.js:56:35

      - postcss.js:150 creator
        [test-stellar]/[postcss]/lib/postcss.js:150:35

      - webpack.config.js:180 module
        [test-stellar]/[gatsby]/dist/utils/webpack.config.js:180:86

      - webpack.config.js:565 _callee$
        [test-stellar]/[gatsby]/dist/utils/webpack.config.js:565:13

      - next_tick.js:131 _combinedTickCallback
        internal/process/next_tick.js:131:7

      - next_tick.js:180 process._tickCallback
        internal/process/next_tick.js:180:9

upgrading gatsby to 1.9.278 does not yield a different result.
And Gatsby 2.0.8 raises a different issue.

**Comment by ChangoMan** [comment]
This starter has been updated to V2. This should be working now
