### ISSUE TITLE
Error during building/develop (Waypoint not found in react-waypoint)

### ISSUE THREAD

**Issue by krerkkiat** [codebushi/gatsby-starter-stellar#4]
"export 'default' (imported as 'Waypoint') was not found in 'react-waypoint'

Basically, this line https://github.com/codebushi/gatsby-starter-stellar/blob/a2b24c5912a6f3e2ef2b66ee97e1ef400b94ea9d/src/pages/index.js#L4

has to be
```
import { Waypoint } from 'react-waypoint'
```

**Comment by ChangoMan** [comment]
Thanks! Just updated and fixed this.
